### ISSUE TITLE
Facebook Integration is not setup properly - Still in Dev Mode

### ISSUE THREAD

**Issue by AUSROGER** [anjosh/htm-project#48]
![image.png](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/822dd74b-a713-4c7a-b26d-26c7a2895bfa)
Go to either Registration or Login page and click Facebook

**Comment by anjosh** [comment]
In order to make Facebook live we would need a Privacy Policy. I found a privacy policy generator but that would cost a bit of money and take some time. I'm going to disable facebook login for now.

**Comment by AUSROGER** [comment]
We should be able to just use the Privacy Policy on the Family Fed Website. I am sure it has been vetted by the legal team
http://familyfed.org/privacy/

Roger Wetherall | M 203-260-2279
wetherallroger@gmail.com

**Comment by anjosh** [comment]
Great. Thanks Roger.

**Comment by anjosh** [comment]
Ok done. Let me know if it works now.
