### ISSUE TITLE
Determine user flow and designs for editing and deleting blessing steps

### ISSUE THREAD

**Issue by anjosh** [anjosh/htm-project#56]
This is assigned to Michael Holmes.
This is blocking #38 and #42

**Comment by anjosh** [comment]
Done by Michael. Here is what he posted:
https://htm-project.slack.com/archives/CGCBWDGEN/p1554746942001000
>Here's an animation of what I was thinking. A slide effect so there's no double pop-ups. The delete can be a small mini pop up "are you sure"
![jackspouse](https://user-images.githubusercontent.com/2905269/55896782-16a5ed00-5b8d-11e9-8616-a19f99ff8c96.gif)

**Comment by anjosh** [comment]
@mikiekwoods could you remove the Notes and location fields since we don't have that information yet? Also, do you think we need the spouse information if we already have it in the person view?

**Comment by mikiekwoods** [comment]
![removednotes.png](https://images.zenhubusercontent.com/5c92b6a2a7f08c1a3af99706/8716e7d1-110b-43c4-9162-42593f7f616f)

**Comment by anjosh** [comment]
Could you show it in the context of the page? I think there might be too much whitespace.

**Comment by anjosh** [comment]
@mikiekwoods Could you take a look at my last comment?

**Comment by mikiekwoods** [comment]
![wriframesmytribe2](https://user-images.githubusercontent.com/37634342/56998520-68c0a980-6b60-11e9-9ce9-a6eb2ff57417.png)
I think a bit of white space at the bottom is okay. It'll fill up when there's more features.

**Comment by anjosh** [comment]
Ok thanks. Will mark this done.
