### ISSUE TITLE
Email Verification Needs to be re-formatted

### ISSUE THREAD

**Issue by AUSROGER** [anjosh/htm-project#61]
![image.png](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/de270217-386b-49e8-9235-d2b7b5d482e7)
The attached image shows the verification email. This needs to be formatted better to make it consistent with the website

**Comment by AUSROGER** [comment]
i checked this in various email clients and it looks like it is just unique to my Windows Mail program which nobody really uses

**Comment by anjosh** [comment]
Ah ok. That's good to hear. I'll move this to Done then.
