### ISSUE TITLE
Blessing Steps are being duplicated

### ISSUE THREAD

**Issue by AUSROGER** [anjosh/htm-project#62]
![image.png](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/2dd91e1e-f5de-4724-bb8e-bdcaae860c5a)![image.png](https://images.zenhubusercontent.com/5c92d4ca8dcdbd6b61379ffe/43765be6-ff14-49f6-a605-7d4304d9bece)
I am not sure why these steps are being duplicated for some people but not for others when a list is imported.

**Comment by anjosh** [comment]
Great glad you found this issue. Will look into it.

**Comment by anjosh** [comment]
This should be fixed now. Let me know.

**Comment by anjosh** [comment]
@AUSROGER Let me know if it looks fixed to you
