### ISSUE TITLE
Cannot Add Pictures to contacts

### ISSUE THREAD

**Issue by AUSROGER** [anjosh/htm-project#63]
Edit an existing contact > Add a Picture > Upload a File> Save the record > Go back to the list view. 
The picture does not appear next to the person's name.

**Comment by anjosh** [comment]
Hi Roger. I'm unable to reproduce the issue. There was a major issue with the database which I just fixed. Could you see this is still not working?

**Comment by anjosh** [comment]
@AUSROGER did you see my last comment?
