### ISSUE TITLE
As Henry (HTMA Leader) I should be able to see a dashboard showing number of HTM Accomplishers

### ISSUE THREAD

**Issue by anjosh** [anjosh/htm-project#68]
Karlsun and I spoke and the first step we landed on for this is to combine all the data we have at the moment in spreadsheets to create charts that show some of the necessary metrics we want to measure and make those charts and data update automatically.

For the first phase we want to show metrics similar to those in the [Slide Series for TM Tuesday Report presentation](https://docs.google.com/presentation/d/1Wls3hzNMjEX9_OPGLDwEguf8WWo0crwqi1GX9yYfhIM/edit?ts=5cc36318#slide=id.g45413ca169_1_18) 

By taking the data from the [District W+E Blessing Tracker spreadsheet](https://docs.google.com/spreadsheets/d/1PpfLV5R_nKOiVBch_OBy6Q1lNGSx4qcbzTiX6LKue1U/edit?ts=5cc3619f#gid=1791810389)

And setting it up so that this will automatically be updated when people fill out the [Report Your Blessings Form on TribeNet](https://tribenet.co/enter-your-blessings-below/)

**Comment by anjosh** [comment]
This could be said to be part of #43

**Comment by mikiekwoods** [comment]
This is all happening in the app?

**Comment by anjosh** [comment]
Not now. Eventually we want reporting to happen automatically as people enter their contacts information in the app.

**Comment by anjosh** [comment]
It is not completely automatic but close: https://docs.google.com/spreadsheets/d/1PpfLV5R_nKOiVBch_OBy6Q1lNGSx4qcbzTiX6LKue1U/edit?ts=5cc3619f#gid=2067644459

Deeming this ready to be reviewed.
