### ISSUE TITLE
As Tim, I should be able to click one page for information on using the app

### ISSUE THREAD

**Issue by mikiekwoods** [anjosh/htm-project#73]
Feedback Page to Help Page (with How to Videos, FAQ, and contact for feedback and help)

Maybe when first logging in on a new account, this is the first page you see.

Nancy and I talked about two main how-tos. Storing Contacts & Follow Up with Contacts.

**Comment by anjosh** [comment]
Ok sounds good. Some designs would be very helpful.

**Comment by anjosh** [comment]
With the in-app tutorial now online, I would say this isn't necessary at the moment. @mikiekwoods feel free to re-open it if you think it is.
