### ISSUE TITLE
As Tim, I should be able send text message templates to follow up with my contacts

### ISSUE THREAD

**Issue by mikiekwoods** [anjosh/htm-project#74]
Looks like this is possible: https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link

You may need to check if it is iOs or Android and format it differently

**Comment by anjosh** [comment]
Is this something that you and Nancy felt was important?

**Comment by mikiekwoods** [comment]
No this is what I thought could be a good feature and pretty easy to
implement I think. Not urgent but could add a lot of value.

**Comment by anjosh** [comment]
Just saw your comment today. I agree. It's on my radar.
